application:
  port: 8000
  base_url: "http://127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  database_name: "newsletter"
  username: "user"
  password: "password123"
email_client:
  base_url: "localhost"
  sender_email: "test_email@address.com"
  auth_token: "authorizationTokenToBeAdded"
  timeout_milliseconds: 6000
